# This rule is not used by the project custom-controller-kubebuilder itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to store.crd.com resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: custom-controller-kubebuilder
    app.kubernetes.io/managed-by: kustomize
  name: book-viewer-role
rules:
- apiGroups:
  - store.crd.com
  resources:
  - books
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - store.crd.com
  resources:
  - books/status
  verbs:
  - get
