apiVersion: store.crd.com/v1
kind: Book
metadata:
  labels:
    app.kubernetes.io/name: custom-controller-kubebuilder
    app.kubernetes.io/managed-by: kustomize
  name: book-sample
spec:
  deploymentName: example-book
  replicas: 0
  container:
    name: book-store
    image: shiponcs/book-store-api-server
    ports:
      - containerPort: 8080
